# Generated by Django 6.0.3 on 2026-03-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('engine', models.CharField(max_length=50)),
                ('power', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=50)),
                ('consumption', models.FloatField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
