# Generated by Django 6.0.3 on 2026-03-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_acceleration_car_adaptive_cruise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='length',
            field=models.IntegerField(default=4500),
        ),
        migrations.AddField(
            model_name='car',
            name='weight',
            field=models.IntegerField(default=1500),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive',
            field=models.CharField(choices=[('FWD', 'Przedni napęd'), ('RWD', 'Tylny napęd'), ('AWD', 'Napęd na 4 koła')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('electric', 'Elektryczny'), ('petrol', 'Benzyna'), ('diesel', 'Diesel'), ('hybrid', 'Hybryda')], max_length=20),
        ),
    ]
