# Generated by Django 6.0.3 on 2026-03-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_length_car_weight_alter_car_drive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='abs_system',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='airbags',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('suv', 'SUV'), ('wagon', 'Kombi')], default='sedan', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='co2_emission',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='cylinders',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='car',
            name='esp_system',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_tank',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='car',
            name='range_petrol',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='car',
            name='segment',
            field=models.CharField(choices=[('A', 'Miejskie'), ('B', 'Kompaktowe'), ('C', 'Średnie'), ('D', 'Premium'), ('SUV', 'SUV')], default='C', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive',
            field=models.CharField(choices=[('FWD', 'Przedni'), ('RWD', 'Tylny'), ('AWD', '4x4')], max_length=10),
        ),
    ]
