from django.db import migrations


SHOWCASE_CARS = [
    {
        "brand": "Audi",
        "model": "A3 Sportback",
        "year": 2022,
        "price": 124900,
        "image_path": "cars/AudiA3.jpg",
        "engine": "1.5 TFSI",
        "power": 150,
        "fuel_type": "petrol",
        "drive": "FWD",
        "gearbox": "automatic",
        "consumption": 5.9,
        "acceleration": 8.4,
        "max_speed": 224,
        "doors": 5,
        "seats": 5,
        "trunk_capacity": 380,
        "weight": 1320,
        "length": 4340,
        "color": "szary",
        "battery_kwh": None,
        "range_km": None,
        "fuel_tank": 50,
        "range_petrol": 760,
        "cylinders": 4,
        "co2_emission": 0,
        "segment": "C",
        "body_type": "hatchback",
        "cost_per_100km": 0,
        "yearly_cost": 0,
        "abs_system": True,
        "esp_system": True,
        "airbags": 6,
        "heated_seats": True,
        "ventilated_seats": False,
        "leather_seats": False,
        "sunroof": False,
        "panoramic_roof": False,
        "touchscreen": True,
        "navigation": True,
        "bluetooth": True,
        "parking_sensors": True,
        "parking_camera": True,
        "automatic_parking": False,
        "cruise_control": True,
        "adaptive_cruise": False,
        "lane_assist": True,
        "blind_spot_monitor": False,
        "keyless_entry": True,
        "push_start": True,
        "air_conditioning": True,
        "dual_zone_climate": True,
        "heated_steering_wheel": False,
        "ambient_lighting": True,
    },
    {
        "brand": "BMW",
        "model": "320i",
        "year": 2021,
        "price": 149900,
        "image_path": "cars/bmw-3.jpg",
        "engine": "2.0 Turbo",
        "power": 184,
        "fuel_type": "petrol",
        "drive": "RWD",
        "gearbox": "automatic",
        "consumption": 6.7,
        "acceleration": 7.4,
        "max_speed": 235,
        "doors": 4,
        "seats": 5,
        "trunk_capacity": 480,
        "weight": 1505,
        "length": 4709,
        "color": "granatowy",
        "battery_kwh": None,
        "range_km": None,
        "fuel_tank": 59,
        "range_petrol": 780,
        "cylinders": 4,
        "co2_emission": 0,
        "segment": "D",
        "body_type": "sedan",
        "cost_per_100km": 0,
        "yearly_cost": 0,
        "abs_system": True,
        "esp_system": True,
        "airbags": 6,
        "heated_seats": True,
        "ventilated_seats": False,
        "leather_seats": True,
        "sunroof": False,
        "panoramic_roof": False,
        "touchscreen": True,
        "navigation": True,
        "bluetooth": True,
        "parking_sensors": True,
        "parking_camera": True,
        "automatic_parking": False,
        "cruise_control": True,
        "adaptive_cruise": True,
        "lane_assist": True,
        "blind_spot_monitor": True,
        "keyless_entry": True,
        "push_start": True,
        "air_conditioning": True,
        "dual_zone_climate": True,
        "heated_steering_wheel": True,
        "ambient_lighting": True,
    },
    {
        "brand": "BMW",
        "model": "330e",
        "year": 2022,
        "price": 174900,
        "image_path": "cars/bmw-3B.jpg",
        "engine": "2.0 Plug-in Hybrid",
        "power": 292,
        "fuel_type": "hybrid",
        "drive": "RWD",
        "gearbox": "automatic",
        "consumption": 1.8,
        "acceleration": 5.9,
        "max_speed": 230,
        "doors": 4,
        "seats": 5,
        "trunk_capacity": 375,
        "weight": 1815,
        "length": 4709,
        "color": "granatowy",
        "battery_kwh": None,
        "range_km": None,
        "fuel_tank": 40,
        "range_petrol": 600,
        "cylinders": 4,
        "co2_emission": 0,
        "segment": "D",
        "body_type": "sedan",
        "cost_per_100km": 0,
        "yearly_cost": 0,
        "abs_system": True,
        "esp_system": True,
        "airbags": 6,
        "heated_seats": True,
        "ventilated_seats": False,
        "leather_seats": True,
        "sunroof": False,
        "panoramic_roof": True,
        "touchscreen": True,
        "navigation": True,
        "bluetooth": True,
        "parking_sensors": True,
        "parking_camera": True,
        "automatic_parking": True,
        "cruise_control": True,
        "adaptive_cruise": True,
        "lane_assist": True,
        "blind_spot_monitor": True,
        "keyless_entry": True,
        "push_start": True,
        "air_conditioning": True,
        "dual_zone_climate": True,
        "heated_steering_wheel": True,
        "ambient_lighting": True,
    },
    {
        "brand": "Tesla",
        "model": "Model 3",
        "year": 2023,
        "price": 189900,
        "image_path": "cars/Tesla3.jpg",
        "engine": "Electric",
        "power": 283,
        "fuel_type": "electric",
        "drive": "RWD",
        "gearbox": "automatic",
        "consumption": 14.8,
        "acceleration": 6.1,
        "max_speed": 201,
        "doors": 4,
        "seats": 5,
        "trunk_capacity": 542,
        "weight": 1765,
        "length": 4694,
        "color": "niebieski",
        "battery_kwh": 60,
        "range_km": 491,
        "fuel_tank": 0,
        "range_petrol": 0,
        "cylinders": 0,
        "co2_emission": 0,
        "segment": "D",
        "body_type": "sedan",
        "cost_per_100km": 0,
        "yearly_cost": 0,
        "abs_system": True,
        "esp_system": True,
        "airbags": 8,
        "heated_seats": True,
        "ventilated_seats": False,
        "leather_seats": False,
        "sunroof": False,
        "panoramic_roof": True,
        "touchscreen": True,
        "navigation": True,
        "bluetooth": True,
        "parking_sensors": True,
        "parking_camera": True,
        "automatic_parking": True,
        "cruise_control": True,
        "adaptive_cruise": True,
        "lane_assist": True,
        "blind_spot_monitor": True,
        "keyless_entry": True,
        "push_start": True,
        "air_conditioning": True,
        "dual_zone_climate": True,
        "heated_steering_wheel": True,
        "ambient_lighting": True,
    },
    {
        "brand": "Toyota",
        "model": "Corolla Touring Sports",
        "year": 2021,
        "price": 109900,
        "image_path": "cars/COROLLA.jpg",
        "engine": "1.8 Hybrid",
        "power": 140,
        "fuel_type": "hybrid",
        "drive": "FWD",
        "gearbox": "automatic",
        "consumption": 4.7,
        "acceleration": 9.4,
        "max_speed": 180,
        "doors": 5,
        "seats": 5,
        "trunk_capacity": 598,
        "weight": 1370,
        "length": 4650,
        "color": "biały",
        "battery_kwh": None,
        "range_km": None,
        "fuel_tank": 43,
        "range_petrol": 850,
        "cylinders": 4,
        "co2_emission": 0,
        "segment": "C",
        "body_type": "wagon",
        "cost_per_100km": 0,
        "yearly_cost": 0,
        "abs_system": True,
        "esp_system": True,
        "airbags": 7,
        "heated_seats": True,
        "ventilated_seats": False,
        "leather_seats": False,
        "sunroof": False,
        "panoramic_roof": False,
        "touchscreen": True,
        "navigation": True,
        "bluetooth": True,
        "parking_sensors": True,
        "parking_camera": True,
        "automatic_parking": False,
        "cruise_control": True,
        "adaptive_cruise": True,
        "lane_assist": True,
        "blind_spot_monitor": False,
        "keyless_entry": True,
        "push_start": True,
        "air_conditioning": True,
        "dual_zone_climate": True,
        "heated_steering_wheel": False,
        "ambient_lighting": False,
    },
    {
        "brand": "Lexus",
        "model": "NX 350h",
        "year": 2024,
        "price": 249900,
        "image_path": "cars/lexus.jpg",
        "engine": "2.5 Hybrid",
        "power": 244,
        "fuel_type": "hybrid",
        "drive": "AWD",
        "gearbox": "automatic",
        "consumption": 5.8,
        "acceleration": 7.7,
        "max_speed": 200,
        "doors": 5,
        "seats": 5,
        "trunk_capacity": 545,
        "weight": 1825,
        "length": 4660,
        "color": "grafitowy",
        "battery_kwh": None,
        "range_km": None,
        "fuel_tank": 55,
        "range_petrol": 900,
        "cylinders": 4,
        "co2_emission": 0,
        "segment": "SUV",
        "body_type": "suv",
        "cost_per_100km": 0,
        "yearly_cost": 0,
        "abs_system": True,
        "esp_system": True,
        "airbags": 8,
        "heated_seats": True,
        "ventilated_seats": True,
        "leather_seats": True,
        "sunroof": True,
        "panoramic_roof": True,
        "touchscreen": True,
        "navigation": True,
        "bluetooth": True,
        "parking_sensors": True,
        "parking_camera": True,
        "automatic_parking": True,
        "cruise_control": True,
        "adaptive_cruise": True,
        "lane_assist": True,
        "blind_spot_monitor": True,
        "keyless_entry": True,
        "push_start": True,
        "air_conditioning": True,
        "dual_zone_climate": True,
        "heated_steering_wheel": True,
        "ambient_lighting": True,
    },
]


def seed_showcase_cars(apps, schema_editor):
    Car = apps.get_model("cars", "Car")

    for car_data in SHOWCASE_CARS:
        Car.objects.update_or_create(
            brand=car_data["brand"],
            model=car_data["model"],
            year=car_data["year"],
            defaults=car_data,
        )


def remove_showcase_cars(apps, schema_editor):
    Car = apps.get_model("cars", "Car")

    for car_data in SHOWCASE_CARS:
        Car.objects.filter(
            brand=car_data["brand"],
            model=car_data["model"],
            year=car_data["year"],
            created_by__isnull=True,
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0009_reset_demo_users"),
    ]

    operations = [
        migrations.RunPython(seed_showcase_cars, remove_showcase_cars),
    ]
